# This workflow will build a Java project with Gradle
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      checks: write
      contents: read
      packages: read
      statuses: read
    strategy:
      matrix:
        java: [ '11', '16' ]
    name: Java ${{ matrix.java }} Build
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/build
        key: ${{ runner.os }}-gradle-jdk${{ matrix.java }}-${{ hashFiles('**/build.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-jdk${{ matrix.java }}-${{ hashFiles('**/build.gradle*') }}
    - name: Assemble Source Files
      run: gradle assemble --warn
      timeout-minutes: 4
    - name: Run tests
      run: gradle check --continue --warn
      timeout-minutes: 4
    - name: Upload Tests Results
      uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: JVM${{ matrix.java }}-Tests
        path: |
          /home/runner/work/MathTools/MathTools/numbers/build/reports/tests/unit-test/aggregated-results
        retention-days: 60