# This workflow will build a Java project with Gradle
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        java: [ '11', '17' ]
    name: Java ${{ matrix.java }} Build
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'
    - name: Assemble from Source Files
      uses: dk96-os/gradle-build-action@f072fadb5d29e34b7cf590cccb61cb82b4e6311f
      with:
        gradle-version: 7.4.1
        arguments: assemble --warn
      timeout-minutes: 4
    - name: Run Tests
      uses: dk96-os/gradle-build-action@f072fadb5d29e34b7cf590cccb61cb82b4e6311f
      with:
        gradle-version: 7.4.1
        arguments: check --continue --warn
      timeout-minutes: 4
    - name: Upload Tests Results
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: JVM${{ matrix.java }}-Tests
        path: |
          /home/runner/work/MathTools/MathTools/generators/build/reports/tests/unit-test/aggregated-results
        retention-days: 60
      timeout-minutes: 1
