# This workflow tests master branch pushes and pull requests

name: CI Run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    
    name: CI Run
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'temurin'
    
    - name: Build
      run: |
        ./gradlew assemble --info
      timeout-minutes: 4
    
    #- uses: ./.github/workflows/test_report
    #  if: success()
    #  timeout-minutes: 2

    #- uses: ./.github/workflows/coverage_report
    #  if: success()
    #  timeout-minutes: 2
    
    #- uses: ./.github/workflows/coverage_verification
    #  if: success()
    #  timeout-minutes: 2
