# This workflow tests master branch pushes and pull requests

name: CI Run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    strategy:
      matrix:
        java: [ '11', '17' ]
    
    name: Build - Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'
    
    - name: Build
      uses: gradle/gradle-build-action@adcc4faa556bcd969fd48d5b88ec5150aee499fa
      with:
        gradle-version: 7.4.1
        arguments: assemble --info
      timeout-minutes: 4
    
    - uses: ./.github/workflows/test_report
      if: success()
      timeout-minutes: 5

    - uses: ./.github/workflows/coverage_report
      if: success()
      timeout-minutes: 5
    
    - uses: ./.github/workflows/coverage_verification
      if: success()
      timeout-minutes: 5
