
name: Code Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]  

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: write
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Run JaCoCo Test Report
        uses: gradle/gradle-build-action@5a7191522fb1962ef05958018b6bccf6db2fa837
        with:
          gradle-version: 7.4
          arguments: jacocoTestReport --warn
        timeout-minutes: 4
      - name: Upload Tests Results
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: JaCoCo Reports
          path: |
            /home/runner/work/MathTools/MathTools/lists/build/jacocoReport/
            /home/runner/work/MathTools/MathTools/numbers/build/jacocoReport/
            /home/runner/work/MathTools/MathTools/statistics/build/jacocoReport/
          retention-days: 90
        timeout-minutes: 1
      - name: JaCoCo Verification
        uses: gradle/gradle-build-action@5a7191522fb1962ef05958018b6bccf6db2fa837
        with:
          gradle-version: 7.4
          arguments: jacocoTestCoverageVerification --warn
        timeout-minutes: 4
