# This workflow verfies the code coverage minimum is met

name: Coverage Verification
on:
  workflow_call:

jobs:
  coverage-verification:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: Coverage Verification
    steps:
    - name: Verify Coverage
      uses: gradle/gradle-build-action@adcc4faa556bcd969fd48d5b88ec5150aee499fa
      with:
        gradle-version: 7.4.1
        arguments: jacocoTestCoverageVerification --warn
      timeout-minutes: 4
