# This workflow verfies the code coverage minimum is met

name: Coverage Verification
on:
  workflow_call:

jobs:
  coverage-verification:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: Coverage Verification
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'temurin'
    - name: Verify Coverage
      run: ./gradlew jacocoTestCoverageVerification --warn
      timeout-minutes: 4
