# This workflow creates code coverage reports

name: Coverage Report
on:
  workflow_call:

jobs:
  coverage-report:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: Code Coverage
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Run JaCoCo Test Report
      run: ./gradlew jacocoTestReport --warn
      timeout-minutes: 3
    
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: Coverage-Report
        path: |
          /home/runner/work/MathTools/MathTools/lists/build/jacocoReport/
          /home/runner/work/MathTools/MathTools/numbers/build/jacocoReport/
          /home/runner/work/MathTools/MathTools/statistics/build/jacocoReport/
          /home/runner/work/MathTools/MathTools/generators/build/jacocoReport/
        retention-days: 60
      timeout-minutes: 1