# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master, Actions ]
  pull_request:
    branches: [ master, Actions ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '8', '11', '15' ]
    name: Java ${{ matrix.java }} Build
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'
    - name: Build with Gradle
      run: gradle build
      timeout-minutes: 3
      shell: bash
    - name: Run tests with Gradle
      run: gradle test
      timeout-minutes: 2
