# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, Actions ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '8', '11' ]
    name: Java ${{ matrix.java }} Build
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'
    - name: Run tests
      run: |
        gradle --build-cache check --continue --info --warning-mode=all
      timeout-minutes: 5
    - name: Build with Gradle
      run: |
        gradle --build-cache build --scan --info --warning-mode=all --no-watch-fs
        gradle --stop
      timeout-minutes: 5
      shell: bash
    
