# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '11', '16' ]
    name: Java ${{ matrix.java }} Build
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/build
        key: ${{ runner.os }}-gradle-jdk${{ matrix.java }}-${{ hashFiles('**/build.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-jdk${{ matrix.java }}-${{ hashFiles('**/build.gradle*') }}
    - name: Assemble Source Files
      run: gradle assemble --warn
      timeout-minutes: 4
    - name: Run tests
      run: gradle check --continue --warn
      timeout-minutes: 4
    - name: Upload Numbers Tests Results
      uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: Numbers-Tests-Java${{ matrix.java }}
        path: |
          /home/runner/work/MathTools/MathTools/numbers/build/reports/tests/test
          /home/runner/work/MathTools/MathTools/numbers/build/test-results/test
        retention-days: 60
    - name: Upload Systems Tests Results
      uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: Systems-Tests-Java${{ matrix.java }}
        path: |
          /home/runner/work/MathTools/MathTools/systems/build/reports/tests/test
          /home/runner/work/MathTools/MathTools/systems/build/test-results/test
        retention-days: 60
    - name: Upload Lists Tests Results
      uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: Lists-Tests-Java${{ matrix.java }}
        path: |
          /home/runner/work/MathTools/MathTools/lists/build/reports/tests/test
          /home/runner/work/MathTools/MathTools/lists/build/test-results/test
        retention-days: 60
    - name: Upload Statistics Tests Results
      uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: Statistics-Tests-Java${{ matrix.java }}
        path: |
          /home/runner/work/MathTools/MathTools/statistics/build/reports/tests/test
          /home/runner/work/MathTools/MathTools/statistics/build/test-results/test
        retention-days: 60