# Create and Publish repository Packages

name: Publish Packages for Release

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    name: Publish Release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
        
      - name: Check Build
        run: ./gradlew check --warn
        timeout-minutes: 7
      
      - name: Generate JavaDoc
        run: ./gradlew dokkaJavadoc --warn
        if: success()
        timeout-minutes: 3
      
      - name: Generate Markdown
        run: ./gradlew dokkaGfm --warn
        if: success()
        timeout-minutes: 3
      
      - name: Publish Packages
        run: ./gradlew publish --warn
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload JavaDoc and Markdown
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: JavaDocs-${{ matrix.java }}
          path: |
            /home/runner/work/MathTools/MathTools/lists/build/dokka/
            /home/runner/work/MathTools/MathTools/lists-ktx/build/dokka/
            /home/runner/work/MathTools/MathTools/numbers/build/dokka/
            /home/runner/work/MathTools/MathTools/statistics/build/dokka/
            /home/runner/work/MathTools/MathTools/generators/build/dokka/
          retention-days: 60
        timeout-minutes: 1
