# Create and Publish repository Packages

name: Publish Packages for Release

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/build
          key: ${{ runner.os }}-gradle-jdk11-${{ hashFiles('**/build.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-jdk11-${{ hashFiles('**/build.gradle*') }}
      - name: Publish package
        run: gradle publish --warn --fail-fast
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}