# This workflow runs tests

name: Test
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    name: Test Report
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Run Tests
      run: ./gradlew check --continue --warn
      timeout-minutes: 4

    - name: Upload Test Reports
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: MT-TestReport
        path: /home/runner/work/*/*/*/build/reports/tests/
        retention-days: 60
        if-no-files-found: error
      timeout-minutes: 1

    - name: Run JaCoCo Test Report
      if: success()
      run: ./gradlew jacocoTestReport --warn
      timeout-minutes: 3

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: Coverage-Report
        path: /home/runner/work/*/*/*/build/jacocoReport/
        retention-days: 60
      timeout-minutes: 1

    - name: Verify Coverage
      if: success()
      run: ./gradlew jacocoTestCoverageVerification --warn
      timeout-minutes: 4
